#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-gherkin
Version  : 4.0.0
Release  : 12
URL      : https://rubygems.org/downloads/gherkin-4.0.0.gem
Source0  : https://rubygems.org/downloads/gherkin-4.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
[![Build Status](https://secure.travis-ci.org/cucumber/gherkin-ruby.svg)](http://travis-ci.org/cucumber/gherkin-ruby)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n gherkin-4.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-gherkin.gemspec

%build
export LANG=C
gem build rubygem-gherkin.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
gherkin-4.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/gherkin-4.0.0
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/gherkin-4.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/bin/gherkin-generate-ast
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/bin/gherkin-generate-pickles
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/bin/gherkin-generate-tokens
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/gherkin-ruby.razor
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/gherkin.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/ast_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/ast_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/dialect.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/gherkin-languages.json
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/gherkin_line.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/pickles/compiler.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/token.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/token_formatter_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/token_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/lib/gherkin/token_scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/spec/capture_warnings.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/spec/coverage.rb
/usr/lib64/ruby/gems/2.3.0/gems/gherkin-4.0.0/spec/gherkin/parser_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/gherkin-4.0.0.gemspec
